package com.capgemini.storesmanagementsystem.exception;

public class UserNotFoundException extends RuntimeException{
		   String str1;
		   /* Constructor of custom exception class
		    * here I am copying the message that we are passing while
		    * throwing the exception to a string and then displaying 
		    * that string along with the message.
		    */
		   UserNotFoundException(String str2) {
			str1=str2;
		   }
		   public String toString(){ 
			return ("MyException Occurred: "+str1) ;
		   }
		}

		class Example1{
		   public static void main(String args[]){
			try{
			}
			catch(UserNotFoundException exp){
				System.out.println("Catch Block") ;
				System.out.println(exp) ;
			}
		   }
		}

}
